# Void Linux glibc build configuration for UFI001B
ARCH=aarch64
GLIBC=glibc
VOID_MIRROR=https://alpha.de.repo.voidlinux.org/current

# Kernel (pmOS mainline for MSM8916)
KERNEL_REPO=https://github.com/pmos-on-uefi/uefi-builds
KERNEL_APK=linux-kernel-mainline-6.6.0-msm8916.apk
